
===========Start_RsReceiver============= 02.09.2020 12:07:36
Additional Information:GetSettingsOnConnecting
80;120;102500000;2000000;1250;1;MAX;PER;0,00025;0,1;10000000;200000000;105000000;190000000;1000;250000;FM;PAV;0;50;AUTO;10;0;10;1;1;0
Error Message: Входная строка имела неверный формат.
Stack Trace:    в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   в System.Decimal.Parse(String s)
   в ControlU.Equipment.RsReceiver_v2.GetSettingsOnConnecting() в d:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\RsReceiver_v2.cs:строка 3129
HResult: -2146233033
============End_RsReceiver============== 02.09.2020 12:07:36


===========Start_RsReceiver============= 02.09.2020 12:48:32
Additional Information:GetSettingsOnConnecting
80;120;102500000;2000000;1250;1;MAX;PER;0,00025;0,1;10000000;200000000;105000000;190000000;1000;250000;FM;PAV;0;50;AUTO;10;0;10;1;1;0
Error Message: Входная строка имела неверный формат.
Stack Trace:    в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   в System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   в System.Decimal.Parse(String s)
   в ControlU.Equipment.RsReceiver_v2.GetSettingsOnConnecting() в d:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\RsReceiver_v2.cs:строка 3249
HResult: -2146233033
============End_RsReceiver============== 02.09.2020 12:48:32

10
DEF
001 \"192.168.0.3\", 5556, FSC, MSC, IFP, CW, GPSC, ZSP, \"VOLT:AC\", \"FREQ:OFFS\", \"FSTR\", \"CHAN\", \"FREQ:RX\", \"FREQ:HIGH:RX\", \"PRIV\", \"OPT\", \"IFP\", \"ZSP:VOLT:AC\", \"ZSP:FM\"
002
003
004
005
006
007
008
009

10
DEF
001 \"192.168.0.3\", 5556, IFP, PSC, GPSC, ZSP, \"VOLT:AC\", \"PRIV\", \"OPT\", \"IFP\", \"ZSP:VOLT:AC\", \"ZSP:FM\"
002
003
004
005
006
007
008
009
10
DEF
001 \"192.168.2.3\", 5556, IFP, PSC, GPSC, \"VOLT:AC\", \"PRIV\", \"OPT\", \"IFP\", \"IFP2\"
002
003\r\n004\r\n005\r\n006\r\n007\r\n008\r\n009\r\n"


10
DEF
001 \"192.168.2.3\", 5556, IFP, PSC, GPSC, \"VOLT:AC\", \"PRIV\", \"OPT\", \"IFP\"
002\r\n003\r\n004\r\n005\r\n006\r\n007\r\n008\r\n009\r\n"



"
10
DEF
001 \"192.168.0.3\", 5556, FSC, MSC, IFP, CW, GPSC, ZSP, \"VOLT:AC\", \"FREQ:OFFS\", \"FSTR\", \"CHAN\", \"FREQ:RX\", \"FREQ:HIGH:RX\", \"PRIV\", \"OPT\", \"IFP\", \"ZSP:VOLT:AC\", \"ZSP:FM\"
002 \"192.168.0.3\", 23023, IFP, \"VOLT:AC\", \"FSTR\", \"SWAP\", \"OPT\"
003\r\n004\r\n005\r\n006\r\n007\r\n008\r\n009\r\n"

"10DEF
001 \"192.168.0.3\", 23023, IFP, \"VOLT:AC\", \"FSTR\", \"SWAP\", \"OPT\"
002\r\n003\r\n004\r\n005\r\n006\r\n007\r\n008\r\n009\r\n"

===========Start_RsReceiver============= 03.09.2020 18:41:51
Additional Information:SetFFMRangeLevel
Error Message: Не удается прочитать данные из транспортного соединения: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера.
Stack Trace:    в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   в System.IO.Stream.ReadByte()
   в ControlU.Equipment.TelnetConnection.ReadBytes() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\Classes.cs:строка 325
   в ControlU.Equipment.TelnetConnection.Read() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\Classes.cs:строка 318
   в ControlU.Equipment.TelnetConnection.Query(String str) в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\Classes.cs:строка 264
   в ControlU.Equipment.RsReceiver_v2.SetFFMRangeLevel() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\RsReceiver_v2.cs:строка 6119
HResult: -2146232800
============End_RsReceiver============== 03.09.2020 18:41:52


===========Start_NpgsqlDB============= 04.09.2020 13:59:55
Additional Information:CheckServerIsRunnig
Error Message: Exception while connecting
Stack Trace:    в Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 693
   в Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 618
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnector.<Open>d__148.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 423
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext() в C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:строка 249
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 297
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnection.Open() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 119
   в ControlU.DB.NpgsqlDB_v2.CheckServerIsRunnig() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\DB\NpgsqlDB_v2.cs:строка 390
HResult: -2147467259
============End_NpgsqlDB============== 04.09.2020 13:59:55


===========Start_NpgsqlDB============= 04.09.2020 17:43:09
Additional Information:CheckServerIsRunnig
Error Message: Exception while connecting
Stack Trace:    в Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 693
   в Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 618
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnector.<Open>d__148.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 423
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext() в C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:строка 249
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 297
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnection.Open() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 119
   в ControlU.DB.NpgsqlDB_v2.CheckServerIsRunnig() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\DB\NpgsqlDB_v2.cs:строка 390
HResult: -2147467259
============End_NpgsqlDB============== 04.09.2020 17:43:09


===========Start_NpgsqlDB============= 07.09.2020 18:31:11
Additional Information:CheckServerIsRunnig
Error Message: Exception while connecting
Stack Trace:    в Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 693
   в Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 618
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnector.<Open>d__148.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 423
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext() в C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:строка 249
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 297
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnection.Open() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 119
   в ControlU.DB.NpgsqlDB_v2.CheckServerIsRunnig() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\DB\NpgsqlDB_v2.cs:строка 390
HResult: -2147467259
============End_NpgsqlDB============== 07.09.2020 18:31:11


===========Start_NpgsqlDB============= 09.09.2020 11:05:45
Additional Information:CheckServerIsRunnig
Error Message: Exception while connecting
Stack Trace:    в Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 693
   в Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 618
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnector.<Open>d__148.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 423
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext() в C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:строка 249
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 297
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnection.Open() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 119
   в ControlU.DB.NpgsqlDB_v2.CheckServerIsRunnig() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\DB\NpgsqlDB_v2.cs:строка 390
HResult: -2147467259
============End_NpgsqlDB============== 09.09.2020 11:05:45


===========Start_NpgsqlDB============= 12.09.2020 12:49:16
Additional Information:CheckServerIsRunnig
Error Message: Exception while connecting
Stack Trace:    в Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 693
   в Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 618
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnector.<Open>d__148.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 423
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext() в C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:строка 249
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 297
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnection.Open() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 119
   в ControlU.DB.NpgsqlDB_v2.CheckServerIsRunnig() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\DB\NpgsqlDB_v2.cs:строка 390
HResult: -2147467259
============End_NpgsqlDB============== 12.09.2020 12:49:16


===========Start_NpgsqlDB============= 12.09.2020 20:55:51
Additional Information:CheckServerIsRunnig
Error Message: Exception while connecting
Stack Trace:    в Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 693
   в Npgsql.NpgsqlConnector.<RawOpen>d__152.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 618
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnector.<Open>d__148.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:строка 423
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.ConnectorPool.<AllocateLong>d__28.MoveNext() в C:\projects\npgsql\src\Npgsql\ConnectorPool.cs:строка 249
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Threading.Tasks.ValueTask`1.get_Result()
   в Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 297
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Npgsql.NpgsqlConnection.Open() в C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs:строка 119
   в ControlU.DB.NpgsqlDB_v2.CheckServerIsRunnig() в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\DB\NpgsqlDB_v2.cs:строка 390
HResult: -2147467259
============End_NpgsqlDB============== 12.09.2020 20:55:51


===========Start_TelnetConnection============= 12.09.2020 20:56:43
Additional Information:Open
Error Message: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 192.168.2.10:5555
Stack Trace:    в System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   в ControlU.Equipment.TelnetConnection.Open(String hostname, Int32 port) в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\Classes.cs:строка 388
HResult: -2147467259
============End_TelnetConnection============== 12.09.2020 20:56:43


===========Start_TelnetConnection============= 24.09.2020 12:18:37
Additional Information:Open
Error Message: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера 192.168.2.10:5555
Stack Trace:    в System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   в ControlU.Equipment.TelnetConnection.Open(String hostname, Int32 port) в D:\My Doc\Visual Studio 2017\Projects\3anet\ControlU\Equipment\Classes.cs:строка 388
HResult: -2147467259
============End_TelnetConnection============== 24.09.2020 12:18:37


===========Start_TSMxReceiver============= 07.10.2020 11:55:22
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 11:55:22


===========Start_TSMxReceiver============= 07.10.2020 11:55:24
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 11:55:24


===========Start_TSMxReceiver============= 07.10.2020 11:55:32
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 11:55:32


===========Start_TSMxReceiver============= 07.10.2020 11:55:36
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 11:55:36


===========Start_TSMxReceiver============= 07.10.2020 11:55:37
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 11:55:37


===========Start_TSMxReceiver============= 07.10.2020 12:02:12
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 12:02:12


===========Start_TSMxReceiver============= 07.10.2020 12:02:14
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 12:02:14


===========Start_TSMxReceiver============= 07.10.2020 12:02:15
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 12:02:15


===========Start_TSMxReceiver============= 07.10.2020 12:02:15
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 12:02:15


===========Start_TSMxReceiver============= 07.10.2020 12:02:16
Additional Information:OnWarning
FirmwareOutdated
Error Message: TSMW firmware outdated, please update to version 2.6 or newer.
Stack Trace: 
HResult: -2146233088
============End_TSMxReceiver============== 07.10.2020 12:02:16


